import React, { useState, useEffect } from 'react';
import { 
  Bell, 
  Filter, 
  Search, 
  ShieldAlert, 
  UserCheck, 
  ArrowRight, 
  Briefcase, 
  CheckCircle2, 
  Clock, 
  AlertTriangle,
  Sliders,
  Eye
} from 'lucide-react';
import RiskBadge from '../components/RiskBadge';
import { getRiskAlerts, updateAlertStatus, subscribeToDataChanges } from '../services/api';
import { getRiskColorClass, getStatusBadgeClass } from '../utils/formatters';

export default function RiskAlertsPage({ 
  onNavigateToAccount, 
  onAddToCase 
}) {
  const [alerts, setAlerts] = useState([]);
  const [search, setSearch] = useState('');
  const [severityFilter, setSeverityFilter] = useState('ALL');
  const [statusFilter, setStatusFilter] = useState('ALL');
  const [typeFilter, setTypeFilter] = useState('ALL');
  const [loading, setLoading] = useState(true);

  const loadAlerts = async () => {
    try {
      setLoading(true);
      const data = await getRiskAlerts({
        severity: severityFilter,
        status: statusFilter,
        alertType: typeFilter,
        search
      });
      setAlerts(data);
    } catch (err) {
      console.error('Error loading alerts:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadAlerts();
    const unsub = subscribeToDataChanges(loadAlerts);
    return () => unsub();
  }, [severityFilter, statusFilter, typeFilter, search]);

  const handleStatusChange = async (alertId, newStatus) => {
    await updateAlertStatus(alertId, newStatus);
    loadAlerts();
  };

  return (
    <div className="p-6 space-y-6 max-w-7xl mx-auto">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <h1 className="text-xl font-bold tracking-tight text-white flex items-center gap-2">
              <Bell className="w-5 h-5 text-red-400" />
              Automated Risk & Mule Alerts
            </h1>
            <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-red-500/15 text-red-300 border border-red-500/30">
              {alerts.length} ALERTS ACTIVE
            </span>
          </div>
          <p className="text-xs text-slate-400">
            Real-time triggers generated by heuristic graph rules and velocity anomaly detectors.
          </p>
        </div>
      </div>

      {/* Filter Toolbar */}
      <div className="card-investigation p-4 bg-dark-850 flex flex-wrap items-center justify-between gap-3 text-xs">
        <div className="flex items-center gap-3 flex-wrap">
          {/* Search */}
          <div className="relative">
            <Search className="w-3.5 h-3.5 text-slate-400 absolute left-2.5 top-2.5 pointer-events-none" />
            <input
              type="text"
              placeholder="Search alert, account..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="bg-dark-950 border border-slate-700 rounded-lg pl-8 pr-3 py-1.5 text-xs text-slate-200 focus:outline-none focus:border-indigo-500 font-mono w-48"
            />
          </div>

          {/* Severity */}
          <select
            value={severityFilter}
            onChange={(e) => setSeverityFilter(e.target.value)}
            className="bg-dark-950 border border-slate-700 text-slate-300 text-xs rounded-lg px-2.5 py-1.5 focus:outline-none focus:border-indigo-500"
          >
            <option value="ALL">All Severities</option>
            <option value="CRITICAL">Critical</option>
            <option value="HIGH">High</option>
            <option value="MEDIUM">Medium</option>
            <option value="LOW">Low</option>
          </select>

          {/* Status */}
          <select
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
            className="bg-dark-950 border border-slate-700 text-slate-300 text-xs rounded-lg px-2.5 py-1.5 focus:outline-none focus:border-indigo-500"
          >
            <option value="ALL">All Statuses</option>
            <option value="New">New</option>
            <option value="Investigating">Investigating</option>
            <option value="Escalated">Escalated</option>
            <option value="Resolved">Resolved</option>
            <option value="Dismissed">Dismissed</option>
          </select>

          {/* Alert Type */}
          <select
            value={typeFilter}
            onChange={(e) => setTypeFilter(e.target.value)}
            className="bg-dark-950 border border-slate-700 text-slate-300 text-xs rounded-lg px-2.5 py-1.5 focus:outline-none focus:border-indigo-500"
          >
            <option value="ALL">All Alert Types</option>
            <option value="High transaction velocity">High transaction velocity</option>
            <option value="Multiple unrelated senders">Multiple unrelated senders</option>
            <option value="Rapid onward transfer">Rapid onward transfer</option>
            <option value="Structuring / splitting pattern">Structuring / splitting pattern</option>
            <option value="Suspicious community membership">Suspicious community membership</option>
            <option value="Unusual transaction frequency">Unusual transaction frequency</option>
          </select>
        </div>

        <div className="text-slate-400 font-mono text-[11px]">
          Showing {alerts.length} triggers
        </div>
      </div>

      {/* Alerts Table */}
      <div className="card-investigation overflow-hidden bg-dark-900 border-slate-800">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead>
              <tr className="bg-dark-950 border-b border-slate-800 text-[10px] text-slate-400 uppercase font-semibold">
                <th className="p-3.5">Alert ID</th>
                <th className="p-3.5">Account</th>
                <th className="p-3.5">Risk Score</th>
                <th className="p-3.5">Alert Type</th>
                <th className="p-3.5">Severity</th>
                <th className="p-3.5">Detected Time</th>
                <th className="p-3.5">Status</th>
                <th className="p-3.5">Assigned Analyst</th>
                <th className="p-3.5 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-800/60 font-mono">
              {alerts.length === 0 ? (
                <tr>
                  <td colSpan={9} className="p-8 text-center text-slate-500 font-sans">
                    No alerts match the chosen filter criteria.
                  </td>
                </tr>
              ) : (
                alerts.map((alert) => (
                  <tr key={alert.id} className="hover:bg-slate-800/40 transition">
                    <td className="p-3.5 font-bold text-slate-300">{alert.id}</td>
                    <td className="p-3.5">
                      <button
                        onClick={() => onNavigateToAccount(alert.accountId)}
                        className="font-bold text-indigo-400 hover:text-indigo-300 hover:underline flex items-center gap-1"
                      >
                        {alert.accountId}
                        <ArrowRight className="w-3 h-3 text-slate-500" />
                      </button>
                    </td>
                    <td className="p-3.5">
                      <span className="font-bold text-white">{alert.riskScore}</span>
                      <span className="text-[10px] text-slate-500"> / 100</span>
                    </td>
                    <td className="p-3.5 font-sans font-medium text-slate-200">
                      {alert.alertType}
                    </td>
                    <td className="p-3.5">
                      <RiskBadge level={alert.severity} size="sm" />
                    </td>
                    <td className="p-3.5 text-slate-400 font-sans text-[11px]">{alert.detectedTime}</td>
                    <td className="p-3.5">
                      <select
                        value={alert.status}
                        onChange={(e) => handleStatusChange(alert.id, e.target.value)}
                        className={`text-[11px] font-sans font-semibold rounded px-2 py-0.5 focus:outline-none cursor-pointer ${getStatusBadgeClass(alert.status)}`}
                      >
                        <option value="New">New</option>
                        <option value="Investigating">Investigating</option>
                        <option value="Escalated">Escalated</option>
                        <option value="Resolved">Resolved</option>
                        <option value="Dismissed">Dismissed</option>
                      </select>
                    </td>
                    <td className="p-3.5 font-sans text-slate-300 text-[11px]">{alert.assignedAnalyst}</td>
                    <td className="p-3.5 text-right font-sans">
                      <div className="flex items-center justify-end gap-1.5">
                        <button
                          onClick={() => onNavigateToAccount(alert.accountId)}
                          className="px-2 py-1 rounded bg-indigo-600 hover:bg-indigo-500 text-white text-[11px] font-medium flex items-center gap-1 transition"
                        >
                          <UserCheck className="w-3 h-3" />
                          Investigate
                        </button>
                        <button
                          onClick={() => onAddToCase && onAddToCase({
                            type: 'alert',
                            label: alert.id,
                            detail: `${alert.alertType} on ${alert.accountId}`
                          })}
                          className="p-1 rounded bg-dark-950 hover:bg-slate-700 text-slate-300 hover:text-white transition"
                          title="Add Alert to Case"
                        >
                          <Briefcase className="w-3.5 h-3.5 text-indigo-400" />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
